# Generated by Django 5.1.4 on 2026-03-02 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketprice',
            old_name='current_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='marketprice',
            name='predicted_price',
        ),
        migrations.AddField(
            model_name='marketprice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
