# Generated by Django 5.2.7 on 2026-03-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandi', '0002_rename_current_price_marketprice_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketprice',
            name='predicted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
